language: python 
python:
  - "3.9"

branches:
  only:
    - main

install:
  - cd src/prototype
  - pip install -r requirements.txt
  - pip install -r requirements.env.txt

script:
  - pytest --cov -r w >> tmp.txt
  - curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST -H "Content-Type:text/plain" -d @tmp.txt "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"