language: python 
python:
  - "3.9"

branches:
  only:
    - main

install:
  - cd src/prototype
  - pip install -r requirements.txt
  - pip install -r requirements.env.txt

script:
  - pytest --cov -r w 